/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIDemo */

#ifndef _Included_JNIDemo
#define _Included_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIDemo
 * Method:    doubleValue
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JNIDemo_doubleValue
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
